functests/1node: disable broken symlink test
This test appears to be broken. Presumably the fix is to change the module call
"osd.device" (which doesn't exist) to "osd.osd_devices" (which does exist), but
even with that fix the test still fails, just with a different error:

AttributeError: 'NoneType' object has no attribute 'group'

; line 4

---

{% set osd_id = salt['osd.list']() %}
{% set disk = salt['osd.osd_device'](osd_id[0]) %}    <======================

Signed-off-by: Nathan Cutler <ncutler@suse.com>