populate: dont use double underscored functions from outside
Since python mangles anything inside a class with a double underscore
assuming private methods these would again raise NameErrors.

As an example:

```py
In [1]: def __foo():
   ...:     return 1
   ...:

In [2]: class A():
   ...:     def __init__(self):
   ...:         self.a = 1
   ...:     def bar(self):
   ...:         return __foo() + self.a
   ...:

In [3]: a = A()

In [4]: a.bar()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-4b57aad064bc> in <module>()
----> 1 a.bar()

<ipython-input-2-4bba0c494767> in bar(self)
      3         self.a = 1
      4     def bar(self):
----> 5         return __foo() + self.a
      6

NameError: global name '_A__foo' is not defined
```

Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>