qa: common: ensure minion test result can be parsed
Salt 2017.7.2 has a "feature" where it outputs a traceback immediately after
every salt command. This traceback breaks the result reporting mechanism we use
for our test functions that run on minions. For example:

2018-03-15T11:52:13.817 INFO:teuthology.orchestra.run.target217182141012.stdout:    + echo 'Result: OK'
2018-03-15T11:52:13.886 INFO:teuthology.orchestra.run.target217182141012.stdout:    Result: OK[DEBUG   ] jid 20180315115204426028 found all minions {'target217182141012.teuthology'}
2018-03-15T11:52:13.887 INFO:teuthology.orchestra.run.target217182141012.stdout:
2018-03-15T11:52:13.966 INFO:teuthology.orchestra.run.target217182141012.stdout:Exception ignored in: <bound method AsyncReqMessageClient.__del__ of <salt.transport.zeromq.AsyncReqMessageClient object at 0x7f8344136e48>>
2018-03-15T11:52:13.966 INFO:teuthology.orchestra.run.target217182141012.stdout:Traceback (most recent call last):
2018-03-15T11:52:13.966 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 928, in __del__
2018-03-15T11:52:13.966 INFO:teuthology.orchestra.run.target217182141012.stdout:    self.destroy()
2018-03-15T11:52:13.967 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 919, in destroy
2018-03-15T11:52:13.967 INFO:teuthology.orchestra.run.target217182141012.stdout:    self.stream.io_loop.remove_handler(self.stream.socket)
2018-03-15T11:52:13.967 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 734, in remove_handler
2018-03-15T11:52:13.967 INFO:teuthology.orchestra.run.target217182141012.stdout:    fd, obj = self.split_fd(fd)
2018-03-15T11:52:13.967 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 656, in split_fd
2018-03-15T11:52:13.967 INFO:teuthology.orchestra.run.target217182141012.stdout:    return fd.fileno(), fd
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib64/python3.6/site-packages/zmq/sugar/socket.py", line 157, in fileno
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:    return self.FD
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 45, in __getattr__
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:    return self._get_attr_opt(upper_key, opt)
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 49, in _get_attr_opt
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:    return self.get(opt)
2018-03-15T11:52:13.968 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "zmq/backend/cython/socket.pyx", line 477, in zmq.backend.cython.socket.Socket.get
2018-03-15T11:52:13.969 INFO:teuthology.orchestra.run.target217182141012.stdout:  File "zmq/backend/cython/socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
2018-03-15T11:52:13.969 INFO:teuthology.orchestra.run.target217182141012.stdout:zmq.error.ZMQError: Socket operation on non-socket
2018-03-15T11:52:13.987 INFO:teuthology.orchestra.run.target217182141012.stderr:++ grep -o -P '(?<=Result: )(OK|NOT_OK)$' /tmp/test_script.log
2018-03-15T11:52:13.987 INFO:teuthology.orchestra.run.target217182141012.stderr:++ head -1
2018-03-15T11:52:13.989 INFO:teuthology.orchestra.run.target217182141012.stderr:+ local RESULT=
2018-03-15T11:52:13.990 INFO:teuthology.orchestra.run.target217182141012.stderr:+ test x = xOK
2018-03-15T11:52:13.997 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 89, in run_tasks
    manager.__enter__()
  File "/home/ubuntu/teuthology/teuthology/task/__init__.py", line 121, in __enter__
    self.begin()
  File "/home/ubuntu/src/github.com_SUSE_ceph_ses6/qa/tasks/deepsea.py", line 196, in begin
    cmd
  File "/home/ubuntu/teuthology/teuthology/orchestra/remote.py", line 193, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/ubuntu/teuthology/teuthology/orchestra/run.py", line 403, in run
    r.wait()
  File "/home/ubuntu/teuthology/teuthology/orchestra/run.py", line 166, in wait
    label=self.label)
CommandFailedError: Command failed on target217182141012 with status 1: "sudo sh -c 'cd DeepSea/qa ; suites/basic/health-nfs-ganesha.sh --fsal=both'"

The breakage occurs due to the redirection of both stdout and stderr into the
same file, causing two processes to write to the same file at the same times.
In practice, the output could have been "Result: O[DEBUG ]...K" just as easily
as "Result: OK[DEBUG ]...", rendering any regex matching meaningless.

Signed-off-by: Nathan Cutler <ncutler@suse.com>